version: "3.0"
services:

    nginx:
      container_name: nginx
      build: nginx/
      ports:
        - "80:80"
      restart: on-failure
      networks:
        internal_routes:    
    
    lineservice:
      container_name: lineservice
      build: LineService/ 
      networks:
        internal_routes:
          aliases:
            - lineservice
      restart: on-failure
    
      #    rabbitmq_create_user:
      #image: rabbitmq 
      #ports:
      #  - "5672:5672"
      #networks:
      #  internal_routes:
      #    aliases:
      #      - rabbitmq
    
    
      #accesstoken:
      #container_name: accesstoken
      #build: AccessToken/
      #restart: on-failure
    
    sendnotify:
      container_name: sendnotify
      build: SendNotify/
      restart: on-failure
   
networks:
  internal_routes:
